require 'hoopl' with 'runWithFuel'
ghc-7.4.2 has 'hoopl-3.8.7.3' with accidentally dropped 'runWithFuel' form export.
Later versions have this export restored.

Patch fixes build failure on stock ghc-7.4.2:

> [ 8 of 45] Compiling HN.Optimizer.Dominator ( HN/Optimizer/Dominator.hs, dist/build/spl-test-hunit-exe/spl-test-hunit-exe-tmp/HN/Optimizer/Dominator.o )
> HN/Optimizer/Dominator.hs:15:48: Not in scope: `runWithFuel'

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>